### ISSUE TITLE
Update WebURIServlet

### ISSUE THREAD

**Issue by pdrlps** [cygri/pubby#3]
There's a limitation on pubby when you want to add it to existing Java web applications. If the application has complex servlet filters it will cause some trouble when accessing default pubby URLs (/resource, /page...).

I created a custom WebURL filter to replace the default WebURI filter in _resource/_ URLs, but now the dataset is not available to RDF browsers: it does not reach the WebURIServlet, hence no redirect... Any ideas?

**Comment by cygri** [comment]
Sorry this wasn't answered back when asked. I suppose the question is no longer relevant, so am closing the issue.
