### ISSUE TITLE
Bad conf:supportsIRIs in doc/config.ttl

### ISSUE THREAD

**Issue by MarianoRico** [cygri/pubby#32]
In the master/doc/config.ttl file, in the line 75, the parameter conf:supportsIRIs it is specified in this way:

>  conf:supportsIRIs false;

But pubby crashes. Perhaps it should be so:

>  conf:supportsIRIs "false";

I am using pubby version 0.3.3

**Comment by cygri** [comment]
This has been fixed in the `master` branch, so that it'll work fine with a boolean literal.
