### ISSUE TITLE
Please add release tags

### ISSUE THREAD

**Issue by tillea** [cygri/pubby#36]
Hi,
I'd be interested to package pubby for Debian.  To do so it would be very nice if you would add release tags to the Github repository.  I noticed that you are providing versioned releases from your home page.  Please tag the according commits here to enable easy downloads.
Thanks, Andreas.

**Comment by cygri** [comment]
Andreas, I've gone through the project history and tagged the last commit before each release.

v0.3.3 is the latest release, although lots of changes and improvements were committed after that release.
