### ISSUE TITLE
PREFIX not working in latest version of Pubby

### ISSUE THREAD

**Issue by tariksalihovic** [cygri/pubby#38]
When delcaring own prefix in Pubby e.g. "@prefix dgi: <http://localhost:8080/ontology/> ." -->

The prefix is not showed in the HTML output of classes, properties or individuals. Pubby shows a questionmark (?) before every ObjectProperty. 

Is there any solution to this?

**Comment by cygri** [comment]
This is a bug in the latest published release. It is fixed in the development codebase. If you have Java development tooling (JDK and Maven), you can build from source.
