### ISSUE TITLE
Special characters in URL string return 404 Error

### ISSUE THREAD

**Issue by tariksalihovic** [cygri/pubby#39]
My dataset contains scandinavian characters such as "æøå". When browsing to a ressource containing one of these letters, Pubby return 404 Not Found error. I am browsing to --> http://localhost:8080/ontology/page/harAfhængighed but it returns --> http://localhost:8080/ontology/harAfh%C3%A6ngighed with error "The requested resource does not exist at this server, or no information about it is available." 

Is there any work around?

**Comment by cygri** [comment]
This is already fixed in the codebase (via the introduction of `conf:supportsIRIs`), but the fix is not yet available in a release. If you have Java development tooling (JDK and Maven), you can build from source.
