### ISSUE TITLE
missing URL encoding ?

### ISSUE THREAD

**Issue by ghost** [cygri/pubby#5]
first: a happy new year !

I experienced some problems with pubby, stable release Pubby 0.3.3 .
Indexing some stuff to my triple store a space in a URI is URL-encoded  correctly into a '+'. , i.e. like this:

```
@prefix frbr: <http://purl.org/vocab/frbr/core#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<http://lobid.org/resource/DE-929:Freihand+5-8>
rdf:type frbr:Item .
```

This resource is linked with an other resource in pubby. When I click in pubby to follow that link I got a pubby produced "404 Not Found".
But its working SPARQling 4store directly.

Something similar with url-encoded '/' (which is then a %2F). Following that link in pubby brings up a http-server "page not found" which seems to be because the %2F is by pubby re-interpreted as an '/' - and the so-created link is obviously wrong .
(see  http://lobid.org/resource/HT002511874 , under frbr:exemplar http://test.lobid.org/resource/DE-290:630%2FSchn )
Using 4store as backend, and querying this resource in 4store directly using SPARQL _does_ work (naturally only if I "curl --data-urlencode" the query) .
Again, its working SPARQling 4store directly.

Another problem is with ':' , if I urlencode it pubby doesnot made correct links - if the colon is left decoded pubby works.  

Could it be that pubby follows (internal) URIs without --data-urlencode it  , or am I doing something wrong? 

-o

**Comment by cygri** [comment]
IRIs containing `+`, `:` and `/` all work fine in the current development version. (There are problems with Unicode characters outside of the US-ASCII range, but that's a different issue.)
