### ISSUE TITLE
Conflicting SLF4 jars

### ISSUE THREAD

**Issue by jgeluk** [cygri/pubby#6]
WEB-INF/lib has slf4j-log4j12-1.6.4.jar and slf4j-api-1.5.8.jar causing:

SLF4J: The requested version 1.6 by your slf4j binding is not compatible with [1.5.5, 1.5.6, 1.5.7, 1.5.8]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.

**Comment by cygri** [comment]
Pubby uses Maven now, and doesn't directly depend on slf4j. The versions of slf4j jars pulled in by Pubby's dependencies are all 1.6.4.
